### ISSUE TITLE
3장. 파드: 쿠버네티스에서 컨테이너 실행

### ISSUE THREAD

**Issue by emeraldgoose** [emeraldgoose/k8s_study#3]

**Comment by emeraldgoose** [comment]
# 3.1 파드 소개
여러 프로세스를 단일 컨테이너로 묶지 않는다. 여러 프로세스를 단일 컨테이너 안에서 실행하게 되면 동일한 표준 출력으로 로그를 기록하기 때문에 어떤 프로세스가 남긴 로그인지 파악하기 어렵다. 따라서 각 프로세스는 개별 컨테이너로 실행해야 한다.

파드가 필요한 이유는 여러 프로세스를 단일 컨테이너로 묶지 않기 때문에, 컨테이너를 함께 묶고 하나의 단위로 관리할 수 있는 또 다른 상위 구조가 필요하기 때문이다. 따라서 애플리케이션을 여러 파드로 구성하고, 각 파드에는 밀접하게 관련있는 구성 요소나 프로세스만 포함한다. 여러 컨테이너를 단일 파드에 넣는 경우는 주요 프로세스와 하나 이상의 보완 프로세스로 구성된 경우이다. 예를 들어 주 컨테이너는 웹 서버이고 추가 컨테이너(사이드카 컨테이너)는 로그 로테이터, 수집기 등이 될 수 있다.

**Comment by emeraldgoose** [comment]
# 3.2 YAML 또는 JSON 디스크립터로 파드 생성
쿠버네티스 리소스는 일반적으로 쿠버네티스 REST API 엔트포인트에 JSON 혹은 YAML 매니페스트를 전송해 생성한다. `kubectl get {pod name} -o yaml`명령을 통해 전체 YAML 정의를 볼 수 있다.
```yaml
apiVersion: v1 # 쿠버네티스 API 버전
kind: Pod # 쿠네티스 오브젝트/리소스 유형
metadata: # 파드 메타데이터
  ...
spec: # 파드 정의/내용(파드 컨테이너 목록, 볼륨 등)
  ...
status: # 파드와 그 안의 여러 컨테이너의 상세한 상태
  ...
```
- Metadata : 이름, 네임스페이스, 레이블 및 파드에 관한 정보
- Spec : 파드 컨테이너, 볼륨, 기타 데이터 등 파드 자체에 관한 명세
- Status : 파드 상태, 각 컨테이너 설명과 상태, 파드 내부 IP 등 현재 실행 중인 파드에 관한 현재 정보

파드를 정의하는 기본 파드 매니페스트는 다음과 같다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - image:
     name:
     ports:
     - containerPort:
       protocol: TCP
```

YAML 파일을 이용해 파드를 만들려면, `kubectl create -f {manifest_name.yaml}` 명령을 이용한다. 실행 중인 파드의 전체 정의를 보기 위해 `kubectl get po {pod_name} -o yaml` 명령을 사용한다. json으로 반환하기를 원한다면 `kubectl get po {pod_name} -o json`을 사용하면 된다. 파드 로그를 보기 위해서는 `kubectl logs {pod_name}` 명령을 실행한다. 여러 컨테이너를 포함한 파드의 경우에는 `kubectl logs {pod_name} -c {container_name}` 명령을 사용한다.

파드에 테스트와 디버깅 목적으로 연결하고 싶은 경우가 있는데 서비스를 거치지 않고 특정 파드와 대화하고 싶을 때 쿠버네티스는 해당 파드로 향하는 포트 포워딩을 구성해준다. 포트 포워딩 구성은 `kubectl port-forward {pod_name} {to_port}:{from_port}` 명령으로 할 수 있다.

**Comment by emeraldgoose** [comment]
# 3.3 레이블을 이용한 파드 구성
레이블은 리소스에 첨부하는 키-값 쌍으로 레이블 셀렉터를 사용해 리소스를 선택할 때 활용한다. 레이블 키가 해당 리소스 내에서 고유하다면, 하나 이상 원하는 만큼 레이블을 가질 수 있다.
- app : 파드가 속한 애플리케이션, 구성 요소 혹은 마이크로서비스를 저장한다.
- rel : 파드에서 실행 중인 애플리케이션이 안정(stable), 베타 혹은 카나리(canary) 릴리스인지 보여준다.
파드를 생성할 때 레이블을 붙이는 방법은 다음과 같다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name:
  labels: # 레이블 creation_method=manual과 env=prod를 metadata.labels 섹션에 포함한다.
    creation_method: manual
    env: prod
spec:
  ...
```
`kubectl get pods` 명령은 레이블을 표시하지 않는 것이 기본값이라 --show-labels 스위치를 사용해 레이블을 볼 수 있다. 특정 레이블을 보고 싶다면 `kubectl get po -L {label_value| l label_value1,label_value2,...}` 명령을 사용할 수 있다. 기존 파드에 레이블을 추가하거나 수정하고 싶다면 `kubectl label po {pod_name} {label_key}={label_value}` 명령어를 사용하고 기존 레이블을 수정할 때는 --overwrite 옵션이 필요하다.

**Comment by emeraldgoose** [comment]
# 3.4 레이블 셀렉터를 이용해 파드 부분 집합 나열
레이블 셀렉터는 특정 레이블로 태그된 파드의 부분 집합을 선택해 원하는 작업을 수행한다. 특정 값과 레이블을 갖는지 여부에 따라 리소스를 필터링하는 기준이 된다.
env레이블을 가지고 있지만, 값은 무엇이든 상관없는 파드를 보려면 `kubectl get po -l env` 명령을 사용한다. 만약 env 레이블을 가지고 있지 않은 파드들을 보려면 `kubectl get po -l '!env'` 명령을 사용한다. 마찬가지로 레이블 key에서 value가 아닌 파드들을 보려면 'key!=value'를 사용하고 key에 value1과 value2가 들어있는 파드를 보려면 'key in (value1, value2)'를 사용한다. key에 value1, value2가 들어있지 않은 파드를 보려면 in 대신 notin을 사용한다.

**Comment by emeraldgoose** [comment]
# 3.5 레이블과 셀렉터를 이용해 파드 스케줄링 제한
파드를 스케줄링할 위치를 결정하고 싶을 때 레이블을 이용할 수 있다. 예를 들어, GPU 가속을 제공하는 곳에만 GPU 계산이 필요한 파드를 스케줄링하는 것을 들 수 있다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  nodeSelector: # nodeSelector는 gpu=true 레이블을 포함한 노드에 이 파드를 배포하도록 지시한다.
    gpu: "true"
  containers:
  - image:
    name:
```

**Comment by emeraldgoose** [comment]
# 3.6 파드에 어노테이션 달기
파드 및 다른 오브젝트는 레이블 외에 어노테이션(annotations)을 가질 수 있다. 어노테이션은 키-값 쌍으로 이루어졌고 식별 정보를 갖지 않는다. 어노테이션은 쿠버네티스에 새로운 기능을 추가할 때 흔히 사용된다. 어노테이션이 유용하게 사용되는 경우는 파드나 다른 API 오브젝트에 설명을 추가해두는 것이다. 이렇게 하면 클러스터를 사용하는 모든 사람이 개별 오브젝트에 관한 정보를 신속하게 찾아볼 수 있다.

어노테이션을 추가하기 위해서 `kubectl annotate pod {pod_name} {annotation}` 명령을 이용할 수 있다. `kubectl describe` 명령을 이용해 추가한 어노테이션을 볼 수 있다.

**Comment by emeraldgoose** [comment]
# 3.7 네임스페이스를 사용한 리소스 그룹화
레이블을 이용해 오브젝트들을 그룹으로 묶을 수 있는데 오브젝트들이 여러 레이블을 가질 수 있기 때문에 오브젝트 그룹은 서로 겹쳐질 수 있다. 또한 클러스터에서 작업을 수행하면서 레이블 셀렉터를 명시적으로 사용하지 않는다면 항상 모든 오브젝트를 보게된다. 쿠버네티스는 오브젝트를 네임스페이스로 그룹화하여 복잡한 시스템을 좀 더 작은 개별 그룹으로 분리할 수 있다. 서로 다른 네임스페이스에는 동일한 이름의 리소스를 가질 수 있다. 

먼저 `kubectl get ns` 명령으로 클러스터에 있는 모든 네임스페이스를 나열할 수 있다. `kubectl get po --namespace(-n) {namespace}` 명령으로 네임스페이스를 명시할 수 있다. 

네임스페이스를 생성하기 위해 다음의 매니페스트 파일을 작성할 수 있다.
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {namespace_name}
```
이후 `kubectl create -f {manifest}.yaml` 명령을 통해 해당 파일을 쿠버네티스 API 서버로 전송한다. 또는 `kubectl create namespace {namespace_name}` 명령을 통해 네임스페이스를 생성할 수 있다. 생성한 네임스페이스 안에 리소스를 만들기 위해 metadata 섹션에 namespace: {namespace_name} 항목을 넣거나 `kubectl create -f {manifest}.yaml -n {namespace_name}` 명령을 사용하여 네임스페이스를 지정한다.
