### ISSUE TITLE
4장. 레플리케이션과 그 밖의 컨트롤러: 관리되는 파드 배포

### ISSUE THREAD

**Issue by emeraldgoose** [emeraldgoose/k8s_study#4]

**Comment by emeraldgoose** [comment]
# 4.1 파드를 안정적으로 유지하기
파드가 노드에 스케줄링되면 해당 노드의 Kubelet은 파드의 컨테이너를 실행하고 컨테이너가 계속 실행되도록 한다. 컨테이너의 주 프로세스가 크래시(crash)가 발생된다면 Kubelet이 컨테이너를 다시 시작한다. 만약 프로세스가 크래시가 아닌 작동이 중단되는 경우가 있는데 OutofMemoryErrors를 발생하거나 무한루프, 교착 상태에 빠졌을 때 응답을 하지 않는다면 재시작을 할 수 없을 것이다. 이런 경우 외부에서 애플리케이션의 상태를 체크할 수 있도록 라이브니스 프로브(liveness probe)를 제공한다.

라이브니스 프로브는 컨테이너가 살아 있는지 확인할 수 있다. 파드의 스펙(specification)에 각 컨테이너의 라이브니스 프로브를 지정할 수 있다. 쿠버네티스는 주기적으로 프로브를 실행하여 상태를 체크하고 프로브가 실패할 경우 컨테이너를 다시 시작한다. 쿠버네티스는 세 가지 방법을 통해 컨테이너에 프로브를 실행한다.
- HTTP GET 프로브는 지정한 IP, 포트, 경로에 GET 요청을 보내고 응답 코드가 오류가 아닌경우 프로브가 성공했다고 간주된다.
- TCP 소켓 프로브는 지정된 포트에 TCP 연결을 시도하고 연결에 성공한다면 프로브가 성공한 것이다.
- Exec 프로브는 컨테이너 내 임의의 명령을 실행하고 명령의 종료 상태 코드를 확인하여 상태 코드가 0인 경우 프로브가 성공한 것이다.

HTTP 기반 라이브니스 프로브를 생성하기 위해 매니페스트 파일은 다음과 같이 작성한다.
```yaml
apiVersion: v1
kind: pod
metadata:
  name:
spec:
  containers:
  - image:
    livenessProbe: # GET을 수행하는 라이브니스 프로브
    httpGet:
      path: / # http 요청경로
      port: 8080 # 프로브가 연결해야 하는 포트
```
라이브니스 프로브가 실패하여 컨테이너가 재시작되었다면 `kubectl get`을 실행했을 때 조회된 결과에서 RESTARTS에 카운트가 올라간다. `kubectl describe`로 출력되는 내용을 통해 컨테이너가 다시 시작된 이유를 확인할 수 있다. 결과에 Exit Code값은 128 + x로 계산되고 x가 프로세스에 전송된 시그널을 말한다. 만약, 코드가 137이라면 x는 9이고 이는 프로세스가 강제로 종료되었다는 SIGKILL을 의미한다. 애플리케이션이 재시작되는 시간을 고려해 initialDelaySeconds 속성을 추가할 수 있다.

http get 라이브니스 프로브를 사용할 때 http 엔드포인트에 인증이 필요하지 않은지 확인해야 한다. 그렇지 않으면 프로브가 항상 실패해 컨테이너가 항상 재시작될 수 있다. 또한, 라이브니스 프로브는 많은 연산을 사용하지 않도록 가벼워야 하며, 완료하는 데 너무 오래 걸리지 말아야 한다. 기본적으로 프로브는 자주 실행하고 1초 내에 완료돼야 한다.

**Comment by emeraldgoose** [comment]
# 4.2 레플리케이션컨트롤러 소개
레플리케이션컨트롤러는 쿠버네티스 리소스로서 파드가 항상 실행되도록 보장한다. 파드가 사라지면, 사라진 파드를 감지해 교체 파드를 생성한다. 레플리케이션컨트롤러는 실행 중인 파드의 목록을 지속적으로 모니터링하여 실제 파드 수가 의도하는 수와 일치하는지 확인한다. 파드가 적다면 새 복제본을 만들고 많다면 복제본이 제거된다.

레플리케이션컨트롤러에는 세 가지 필수 요소가 있다.
- 레이블 셀렉터는 레플리케이션컨트롤러의 범위에 잇는 파드를 결정한다.
- 레플리카 수는 실행할 파드의 의도하는 수를 지정한다.
- 파드 템플릿은 새로운 파드 레플리카를 만들 때 사용된다.

레플리케이션컨트롤러를 생성하는 매니페스트 파일은 다음과 같다.
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: # 레플리케이션컨트롤러 이름
spec:
  replicas: 3 # 의도하는 파드 인스턴스 수
  selector: # 파드 셀렉터로 레플리케이션컨트롤러가 관리하는 파드 선택
    key: value
template: # 새 파드에 사용할 파드 템플릿
  metadata:
    labels:
      key: value
  spec:
    containers:
      ...
```
파일을 API서버에 게시하면, 쿠버네티스는 레이블 셀렉터와 일치하는 파드 인스턴스가 3개를 유지하도록 하는 레플리케이션컨트롤러를 생성한다. 레플리케이션컨트롤러의 추가 정보를 확인하고 싶을 때는 `kubectl describe rc {replicationcontroller_name}` 명령을 사용한다.

**Comment by emeraldgoose** [comment]
# 4.3 레플리케이션컨트롤러 대신 레플리카셋 사용하기
레플리카셋은 레플리케이션컨트롤러와 똑같이 동작하지만 좀 더 풍부한 표현식을 사용하는 파드 셀렉터를 갖고 있다. 레플리카셋의 매니페스트 파일은 다음과 같이 작성하고 `kubectl create` 명령을 통해 생성한다. `kubectl get rs` 명령을 통해 레플리카셋이 생성되었는지 확인한다.
```yaml
apiVersion: v1
kind: ReplicaSet
metadata:
  name:
spec:
  replicas: 3
  selector:
    matchLables:
      key: value
  template:
    metadata:
      labels:
        key: value
  spec:
    containers:
      ...
```

레플리카셋에서 표현식을 추가할 수 있는 matchExpressions 셀렉터를 사용할 수 있다. 각 표현식은 키, 연산자, 가능한 값이 포함되어야 한다.
- In은 레이블의 값이 지정된 값 중 하나와 일치해야 한다.
- NotIn은 레이블의 값이 지정된 값과 일치하지 않아야 한다.
- Exists는 파드는 지정된 키를 가진 레이블이 포함돼야 한다. 이 연산자를 사용할 때는 값(value) 필드를 지정하지 않아야 한다.
- DoesNotExist는 파드에 지정된 키를 가진 레이블이 포함돼 있지 않아야 한다. 값 필드를 지정하지 않아야 한다.
여러 포현식을 지정하는 경우 셀렉터가 파드와 매칭되기 위해 모든 표현식이 true여야 한다.

**Comment by emeraldgoose** [comment]
# 4.4 데몬셋을 사용해 각 노드에서 정확히 한 개의 파드 실행하기
레플리카셋은 클러스터 전체에서 무작위로 파드를 분산시키지만 데몬셋은 각 노드에서 하나의 파드 복제본만 실행한다. `kubectl get ds` 명령으로 데몬셋을 확인할 수 있다.
```yaml
apiVersion: v1
kind: DaemonSet
metadata:
  name:
spec:
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      labels:
        key: value
    spec:
      nodeSelector: # 파드 템플릿은 key=value 레이블이 있는 노드를 선택하는 노드 셀렉터를 갖는다.
        key: value
      containers:
        ...
```
노드에 레이블을 추가하는 명령은 `kubectl label node {node_name} {key}={value}`이고 레이블을 변경하려면 --overwrite 옵션을 사용한다.

**Comment by emeraldgoose** [comment]
# 4.5 완료 가능한 단일 태스크를 수행하는 파드 실행
쿠버네티스는 잡(Job) 리소스로 파드의 컨테이너 내부에서 실행 중인 프로세스가 성공적으로 완료되면 컨테이너를 다시 시작하지 않는 파드를 실행할 수 있다. 그렇게되면 파드는 완료된 것으로 간주된다. 노드에 장애가 발생한다면 잡이 관리하는 파드는 레플리카셋과 같은 방식으로 다른 노드로 스케줄링되고 프로세스 자체에 장애가 발생한다면 잡에서 컨테이너를 다시 시작할지 설정할 수 있다. 잡은 작업이 제대로 완료되는 것이 중요한 임시 작업에 유용하다. 잡을 정의하는 매니페스트는 다음과 같다.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:
spec:
  template:
    metadata:
      labels:
        key: value
    spec:
      restartPolicy: OnFailure # 잡은 기본 재시작 정책(Always)을 사용할 수 없다.
      containers:
        ...
```
파드 스펙에서는 restartPolicy를 OnFailure나 Never로 명시적으로 설정해야 한다. 이 설정은 컨테이너가 종료될 때 재시작되지 않도록 하는 것이다. 잡을 확인하려면 `kubectl get jobs` 명령을 사용한다.

잡은 두 개 이상의 파드 인스턴스를 생성해 병렬 또는 순차적으로 실행하도록 구성할 수 있다. 이는 잡 스펙에 completions와 parallelism 속성을 설정해 수행한다. 잡의 매니페스트는 다음과 같다.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:
spec:
  completions: 5 # 잡은 다섯 개의 파드를 순차적으로 실행한다.
  template:
    ...
```
이 잡은 파드를 하나 만들고 파드의 컨테이너가 완료되면 두 번째 파드를 만들어 다섯 개의 파드가 성공적으로 완료될 때까지 반복한다. 파드 중 하나가 실패하면 잡이 새 파드를 생성하므로 잡이 전체적으로 다섯 개 이상의 파드를 생성할 수 있다.

병렬로 잡을 실행하려면 parallelism 속성을 이용하여 병렬로 실행될 파드 수를 지정한다.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:
spec:
  completions: 5
  parallelism: 2
  template:
    ...
```
잡이 수행되는 동안 parallelism 속성을 변경하려면 `kubectl scale job {job_name} --replicas {value}` 명령을 사용한다.

만약 잡이 특정 상태에 빠져 있는 상태라면 activeDeadlineSeconds 속성을 설정해 파드의 실행 시간을 제한할 수 있다. 파드가 오래 실행되면 시스템이 종료를 시도하고 잡을 실패한 것으로 표시한다. spec.backoffLimit 필드를 지정하면 잡을 재시도할 수 있는 횟수를 설정할 수 있다. 명시적으로 지정하지 않으면 기본값을 6이다.

**Comment by emeraldgoose** [comment]
# 4.6 잡을 주기적으로 또는 한 번 실행되도록 스케줄링하기
지정된 간격으로 반복 실행하는 잡을 크론잡(CronJob)이라 한다. 크론잡의 매니페스트는 다음과 같다.
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:
spec:
  schedule: "0 9, 18, * * *"
  jobTemplate: # 크론잡이 생성하는 잡 리소스의 템플릿
    spec:
      template:
        ...
      spec:
        restartPolicy: OnFailure
        containers:
          ...
```
잡이나 파드가 상대적으로 늦게 생성되고 실행될 수 있는데 예정된 시간을 너무 초과해 시작해서는 안되는 요구 사항이 있다면 spec.startingDeadlineSeconds 필드를 지정해 데드라인을 설정할 수 있다. 만약 startingDeadlineSeconds 값이 15이고 스케줄이 "0, 30 * * * *"라면 10:30:00에 실행 예정인 잡이 10:30:15까지 시작하지 않으면 잡이 실행되지 않고 실패로 표시된다.
