### ISSUE TITLE
8장. 애플리케이션에서 파드 메타데이터와 그 외의 리소스에 액세스하기

### ISSUE THREAD

**Issue by emeraldgoose** [emeraldgoose/k8s_study#8]

**Comment by emeraldgoose** [comment]
# 8.1 Downward API로 메타데이터 전달
Downward API로 환경변수 또는 Downward API 볼륨 내 파일로 파드와 해당 환경의 메타데이터를 전달할 수 있다. 컨테이너에 전달 가능한 정보는 다음과 같다.
- 파드의 이름, IP 주소, 속한 네임스페이스, 실행 중인 노드의 이름, 실행 중인 서비스 어카운트 이름
- 각 컨테이너의 CPU와 메모리 요청, 메모리 제한
- 파드의 레이블, 어노테이션
Downward API를 사용하면 애플리케이션을 다시 짜거나 데이터를 가져와서 환경변수에 노출하는 셸 스크립트를 사용하지 않고도 데이터를 애플리케이션에 노출할 수 있다.

환경변수로 파드와 컨테이너의 메타데이터를 컨테이너에 전달하는 방법은 다음과 같다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name:
    image:
    command: ["", ""]
    resources:
      requests:
        cpu: 15m
        memory: 100ki
      limits:
        cpu: 100m
        memory: 4Mi
  env:
  - name: POD_NAME # 환경변수로 노출되는 이름
    valueFrom: # 특정 값을 설정하는 대신 파드 매니페스트의 metadata.name을 참조한다
      fieldRef:
        fieldPath: metadata.name
  -name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_IP
     valueFrom:
       fieldRef:
         fieldPath: status.podIP
- name: NODE_NAME
  valueFrom:
     fieldRef:
       fieldPath: spec.nodeName
- name: SERVICE_ACCOUNT
  valueFrom:
     fieldRef:
       fieldPath: spec.serviceAccountName
- name: CONTAINER_CUP_REQUEST_MILLICORES
  valueFrom:
     resourceFieldRef: # 컨테이너의 CPU/메모리 요청과 제한은 resourceFieldRef를 사용해 참조한다
       resource: reqeusts.cpu
       divisor: 1m
- name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
  valueFrom:
     resourceFieldRef:
       resource: limits.memory
       divisor: 1Ki
```
환경변수 대신 파일로 메타데이터를 노출하려는 경우 downward API 볼륨을 정의해 컨테이너에 마운트할 수 있다. 환경변수로 파드의 레이블이나 어노테이션을 노출할 수 없기 때문에 downwardAPI 볼륨을 사용해야 한다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: downward
  labels: # 레이블과 어노테이션은 downwardAPI 볼륨으로 노출된다
    foo: bar
  annotations:
    key1: value1
    key2: |
      multi
      line
      value
spec:
  containers:
  - name: main
    image: 
    command: ["", ""]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
    limits:
      cpu: 100m
      memory: 4Mi
    volumeMounts: # downward 볼륨은 /etc/downward 아래에 마운트한다
    - name: downward
      mountPath: /etc/downward
volumes:
- name: downward # downwardAPI 볼륨을 downward라는 이름으로 정의한다
  downwardAPI:
    items:
    - path: "podName" # 파드의 이름은 podName 파일에 기록된다
      fieldRef:
        fieldPath: metadata.name # 파드의 레이블은 /etc/downward/labels 파일에 기록된다
    - path: "labels"
      fieldRef:
        fieldPath: metadata.labels
    - path: "annotations"
      fieldRef:
        fieldPath: metadata.annotations # 파드의 어노테이션은 /etc/downward/annotations 파일에 기록한다
    - path: "containerCpuRequestMilliCores"
      resourceFieldRef:
        containerName: main
        resource: requests.cpu
        divisor: 1m
  ...
```
환경변수로 메타데이터를 전달하는 대신 downward라는 볼륨을 정의하고 컨테이너의 /etc/downward 아래에 마운트한다. 이 볼륨에 포함된 파일들은 볼륨 스펙의 downwardAPI.items 속성 아래에 설정된다.
